/**
 * Templates mirror the existing convention set by packages/core-domain and
 * packages/shared-types — not a new convention invented for this tool. Keep
 * these in sync if that convention ever changes.
 */

export function packageJson(name: string, description: string): string {
  const body = {
    name: `@mediafox/${name}`,
    version: '0.1.0',
    private: true,
    type: 'module',
    ...(description ? { description } : {}),
    exports: {
      '.': './dist/index.js',
    },
    types: './dist/index.d.ts',
    files: ['dist'],
    scripts: {
      build: 'tsc -p tsconfig.json',
      typecheck: 'tsc -p tsconfig.json --noEmit',
    },
    devDependencies: {
      '@mediafox/typescript-config': 'workspace:*',
      typescript: '^5.7.2',
    },
  };
  return JSON.stringify(body, null, 2) + '\n';
}

export function tsconfigJson(): string {
  return `{
  "extends": "@mediafox/typescript-config/base.json",
  "compilerOptions": {
    "declaration": true,
    "outDir": "dist",
    "rootDir": "src"
  },
  "include": ["src/**/*.ts"]
}
`;
}

export function indexTs(name: string): string {
  return `/**
 * @mediafox/${name}
 *
 * Generated by \`forge package create\`. Replace this placeholder with the
 * package's real public API — everything a consumer needs should be
 * exported from here, not reached into via internal paths.
 */
export const ${toCamelCase(name)}Placeholder = true as const;
`;
}

export function readmeMd(name: string, description: string): string {
  const heading = `@mediafox/${name}`;
  const desc = description || 'TODO: describe what this package is for.';
  return `# ${heading}

${desc}

## Usage

\`\`\`ts
import { } from '${heading}';
\`\`\`

## Scripts

- \`pnpm --filter ${heading} build\` — compile to \`dist/\`
- \`pnpm --filter ${heading} typecheck\` — type-check without emitting
`;
}

function toCamelCase(kebab: string): string {
  return kebab.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());
}
