-- AlterEnum
ALTER TYPE "MemberRole" ADD VALUE 'TECHNICIAN';

-- AlterEnum
ALTER TYPE "WorkOrderEventType" ADD VALUE 'ARRIVAL_CONFIRMED';
ALTER TYPE "WorkOrderEventType" ADD VALUE 'DIAGNOSIS_RECORDED';
ALTER TYPE "WorkOrderEventType" ADD VALUE 'INTERVENTION_RECORDED';
ALTER TYPE "WorkOrderEventType" ADD VALUE 'VALIDATION_RECORDED';

